### ISSUE TITLE
Usage example is wrong

### ISSUE THREAD

**Issue by volkanunsal** [pablo-co/cartodb-api#4]
Running the client repeatedly using the example only returns the correct result the first time. The reason for that is that each request adds a new method to `@path_steps`. Try for example this:

``` ruby
configuration = CartoDB::Api::Configuration.new
configuration.api_key = '...'
configuration.account = '...'
CartoDB::Api.default_configuration = configuration
cartodb = CartoDB::Api::Request.new(configuration)
cartodb.sql.retrieve params: {q: "SELECT * FROM foo"}
cartodb.sql.retrieve params: {q: "SELECT * FROM bar"}
```

You will get a config like so:

```
=> #<CartoDB::Api::Request:0x007fe1bd35c0e0
 @configuration=
  #<CartoDB::Api::Configuration:0x007fe1c05e7fa0
   @account="...",
   @api_key="...">,
 @path_steps=[:sql, :sql, :sql, :sql, :sql, :sql]>
```

I think it should be clear in the documentation that the user should work on the client returned by the `cartodb.<method>` object.

**Comment by pablo-co** [comment]
@volkanunsal good catch! The Request object is definitely a bit tricky. It's more of a request builder than a request itself. Requests to the API should be independent of each other, which is not true as it stands right now. I think I'll reset the path_steps after each request.
